"""음악 추천 엔진 패키지입니다."""

from .selection import (
    CANDIDATE_SELECTION_TARGET_SIZE,
    FINAL_BUNDLE_SIZE,
    CandidateSelectionInput,
    CandidateSelectionOutput,
    PromptMessage,
    SelectionCandidate,
    SelectionContext,
    SelectionContextSongFeedback,
    SelectionSignals,
    build_candidate_selection_messages,
    build_candidate_selection_system_prompt,
    build_candidate_selection_user_prompt,
    candidate_selection_input_from_state,
    normalize_candidate_pool,
    parse_candidate_selection_output,
)
from .engine import (
    CANDIDATE_POOL_SIZE,
    CandidateRecord,
    CandidateSelector,
    build_candidate_pool,
    llm_select_20_candidates,
    select_final_5,
    verify_with_itunes,
)
from .preference_expansion import (
    PreferenceExpansionInput,
    PreferenceExpansionOutput,
    build_preference_expansion_messages,
    build_preference_expansion_system_prompt,
    build_preference_expansion_user_prompt,
    normalize_expanded_preferences,
    parse_preference_expansion_output,
)
from .upstage_client import (
    UPSTAGE_DEFAULT_CHAT_MODEL,
    UpstageCandidateSelectorClient,
    UpstageEmbeddingClient,
    UpstagePreferenceExpanderClient,
    UpstagePreferenceExpansionError,
    UpstageSelectionError,
)

__all__ = [
    "CANDIDATE_SELECTION_TARGET_SIZE",
    "CANDIDATE_POOL_SIZE",
    "FINAL_BUNDLE_SIZE",
    "CandidateRecord",
    "CandidateSelector",
    "CandidateSelectionInput",
    "CandidateSelectionOutput",
    "PreferenceExpansionInput",
    "PreferenceExpansionOutput",
    "UPSTAGE_DEFAULT_CHAT_MODEL",
    "UpstageEmbeddingClient",
    "UpstageCandidateSelectorClient",
    "UpstagePreferenceExpanderClient",
    "UpstagePreferenceExpansionError",
    "UpstageSelectionError",
    "build_candidate_pool",
    "PromptMessage",
    "llm_select_20_candidates",
    "SelectionCandidate",
    "SelectionContext",
    "SelectionContextSongFeedback",
    "SelectionSignals",
    "build_candidate_selection_messages",
    "build_candidate_selection_system_prompt",
    "build_candidate_selection_user_prompt",
    "build_preference_expansion_messages",
    "build_preference_expansion_system_prompt",
    "build_preference_expansion_user_prompt",
    "candidate_selection_input_from_state",
    "normalize_candidate_pool",
    "normalize_expanded_preferences",
    "parse_candidate_selection_output",
    "parse_preference_expansion_output",
    "select_final_5",
    "verify_with_itunes",
]
