from __future__ import annotations

from backend.app.models import Article


SAMPLE_ARTICLES: list[Article] = [
    Article(
        title="국내 기업, 생성형 AI 업무 도입 확대",
        source="연합뉴스",
        url="https://www.yna.co.kr/view/demo-ai-workflow",
        published_at="2026-06-05T08:10:00+09:00",
        description="국내 주요 기업들이 문서 작성, 고객 응대, 데이터 분석 업무에 생성형 AI를 적용하며 생산성 개선을 추진하고 있다.",
        topic="ai",
    ),
    Article(
        title="출근길 모바일 플랫폼 장애 대응 체계 점검",
        source="연합뉴스",
        url="https://www.yna.co.kr/view/demo-mobile-platform",
        published_at="2026-06-05T07:35:00+09:00",
        description="주요 IT 플랫폼 기업들이 출근 시간대 트래픽 증가에 대비해 클라우드 증설과 장애 대응 체계를 점검하고 있다.",
        topic="it",
    ),
    Article(
        title="수출 기업, 환율 변동성에 가격 전략 재점검",
        source="연합뉴스",
        url="https://www.yna.co.kr/view/demo-export-rate",
        published_at="2026-06-05T06:50:00+09:00",
        description="환율 변동성이 커지면서 수출 기업들이 원가 관리와 해외 판매 가격 전략을 다시 조정하고 있다.",
        topic="economy",
    ),
    Article(
        title="클라우드 보안 투자 늘리는 IT 업계",
        source="ZDNet Korea",
        url="https://zdnet.co.kr/view/demo-cloud-security",
        published_at="2026-06-05T09:20:00+09:00",
        description="서비스형 소프트웨어와 클라우드 전환이 확산되면서 기업 보안 예산이 인증, 접근 제어, 데이터 보호 중심으로 재편되고 있다.",
        topic="it",
    ),
    Article(
        title="AI 반도체 경쟁, 데이터센터 투자 확대와 맞물려 가속",
        source="ZDNet Korea",
        url="https://zdnet.co.kr/view/demo-ai-chip-datacenter",
        published_at="2026-06-05T10:05:00+09:00",
        description="생성형 AI 수요가 늘면서 AI 반도체와 데이터센터 인프라 투자가 동시에 확대되고 있다.",
        topic="ai",
    ),
    Article(
        title="반도체 수출 회복세에 경제 전망 개선",
        source="중앙일보",
        url="https://www.joongang.co.kr/article/demo-chip-export",
        published_at="2026-06-04T18:30:00+09:00",
        description="반도체와 IT 기기 수출이 개선되면서 하반기 경기 회복 기대감이 커지고 있다는 분석이 나왔다.",
        topic="economy",
    ),
    Article(
        title="금융권, AI 상담 시스템 도입 속도 높인다",
        source="중앙일보",
        url="https://www.joongang.co.kr/article/demo-ai-finance",
        published_at="2026-06-05T10:30:00+09:00",
        description="은행과 카드사가 고객 상담, 이상 거래 탐지, 내부 문서 검색에 AI 시스템을 확대 적용하고 있다.",
        topic="ai",
    ),
    Article(
        title="배터리·플랫폼 기업 실적 전망 엇갈려",
        source="중앙일보",
        url="https://www.joongang.co.kr/article/demo-platform-earnings",
        published_at="2026-06-05T08:45:00+09:00",
        description="IT 플랫폼 기업은 광고와 커머스 회복 기대가 커졌지만 일부 제조 업종은 원가 부담으로 실적 전망이 엇갈리고 있다.",
        topic="economy",
    ),
    Article(
        title="금리 동결 전망 속 소비 회복 속도 주목",
        source="한겨레",
        url="https://www.hani.co.kr/arti/demo-rate-consumption",
        published_at="2026-06-04T13:05:00+09:00",
        description="물가와 환율 변동성이 이어지는 가운데 기준금리 동결 가능성과 소비 회복 흐름이 경제 지표의 주요 변수로 거론된다.",
        topic="economy",
    ),
    Article(
        title="AI 윤리 교육 강화하는 대학·기업",
        source="한겨레",
        url="https://www.hani.co.kr/arti/demo-ai-ethics",
        published_at="2026-06-04T14:25:00+09:00",
        description="AI 서비스 확산에 따라 대학과 기업이 개인정보 보호, 편향 완화, 책임 있는 활용을 다루는 교육 과정을 늘리고 있다.",
        topic="ai",
    ),
    Article(
        title="AI 스타트업 투자, 응용 서비스 중심으로 이동",
        source="매일경제",
        url="https://www.mk.co.kr/news/demo-ai-startup",
        published_at="2026-06-04T16:45:00+09:00",
        description="초기 AI 인프라 투자 이후 실제 산업 문제를 해결하는 응용 서비스 기업에 투자 관심이 모이고 있다.",
        topic="startup",
    ),
    Article(
        title="국내 AI 스타트업, 제조 공정 분석 솔루션 출시",
        source="매일경제",
        url="https://www.mk.co.kr/news/demo-ai-manufacturing",
        published_at="2026-06-05T09:55:00+09:00",
        description="한 AI 스타트업이 제조 현장의 불량 원인을 분석하고 생산 효율을 높이는 산업용 AI 솔루션을 공개했다.",
        topic="ai",
    ),
    Article(
        title="코스피, 기술주 강세에 상승 마감",
        source="조선일보",
        url="https://www.chosun.com/economy/demo-kospi-tech",
        published_at="2026-06-05T15:40:00+09:00",
        description="국내 증시는 기술주와 반도체주 강세에 힘입어 상승세로 마감했지만 환율 변동성은 부담 요인으로 지적됐다.",
        topic="stock",
    ),
    Article(
        title="대형 유통사, 데이터 기반 재고 관리 시스템 확대",
        source="조선일보",
        url="https://www.chosun.com/economy/demo-data-inventory",
        published_at="2026-06-05T11:15:00+09:00",
        description="유통업계가 소비 데이터를 분석해 재고와 물류 비용을 줄이는 IT 시스템 투자를 확대하고 있다.",
        topic="it",
    ),
    Article(
        title="중소기업 경기 전망, 수출 회복 기대에 소폭 개선",
        source="조선일보",
        url="https://www.chosun.com/economy/demo-sme-outlook",
        published_at="2026-06-05T07:55:00+09:00",
        description="중소기업 경기 전망 지수가 수출 회복 기대와 내수 소비 개선 전망에 힘입어 소폭 상승했다.",
        topic="economy",
    ),
    Article(
        title="공공기관 AI 도입 가이드라인 논의 본격화",
        source="경향신문",
        url="https://www.khan.co.kr/article/demo-public-ai",
        published_at="2026-06-03T11:10:00+09:00",
        description="공공 영역에서 AI 활용이 늘면서 개인정보 보호, 책임 소재, 투명성 확보를 위한 가이드라인 논의가 이어지고 있다.",
        topic="ai",
    ),
    Article(
        title="채용 시장에서 AI 역량 검증 과제 늘어난다",
        source="경향신문",
        url="https://www.khan.co.kr/article/demo-ai-hiring",
        published_at="2026-06-04T09:30:00+09:00",
        description="기업들이 개발자와 기획자 채용 과정에서 AI 도구 활용 경험과 데이터 해석 능력을 함께 평가하는 사례가 늘고 있다.",
        topic="ai",
    ),
]
